### ISSUE TITLE
Slow build times

### ISSUE THREAD

**Issue by tim-schilling** [djangonaut-space/wagtail-indymeet#126]
**This is a low priority**, but it is a problem. Especially with #124 since a failed deployment requires another deployment to bring the site back up. The build time is currently in the 20-30 minute range which seems like a lot to me for the size of application we have.

If it was possible to reuse the image we use on staging for production, that may make things a bit more manageable as well.

**Comment by dawnwages** [comment]
Unless we want to pay more money, slow build times is intentional. Also, since we have a production and a staging, we should not have a problem with a failed deploy since we can rollback changes on the staging server and the github action will automatically deploy.

What I can do is protect main branch and only allow PRs from develop (idk, we may want the ability to hotfix an issue), add a smoke-test to the CI/CD (non-existent at this point) to develop/staging before we're allowed to merge develop into main branch?
